name: Azure Function Deploy With CICD.
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install required python modules
        run: |
            cd ./MultiTriggerTypeFunctionsDeploy
            python -m pip install --upgrade pip
            pip install --target="./.python_packages/lib/site-packages" -r requirements.txt 

      - name: Zip the Azure Function Deploy folder
        run: |
          cd MultiTriggerTypeFunctionsDeploy
          zip -r ../MultiTriggerTypeFunctionsDeploy.zip ./*

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: "0bd225bd-5239-412e-997a-bcf464dfdf58"
          tenant-id: "f311114e-7747-4f11-b55a-1630bd1e81ce"
          subscription-id: "09d41973-2754-44c5-9bcf-dd5eca4132b2"
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
    
      - name: Build and Deploy to Azure
        run: |
          az functionapp deployment source config-zip \
            --resource-group "githubactiondemo_group" \
            --name "githubactiondemo" \
            --src "./MultiTriggerTypeFunctionsDeploy.zip"
